Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
